FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY src/ ./src/
COPY index.html ./

RUN npm run build 

FROM nginx:alpine AS runner 

COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
